//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONECTION
    {
        public int OBJECTID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public string GUID { get; set; }
        public string VerId { get; set; }
        public Nullable<decimal> cx { get; set; }
        public Nullable<decimal> cy { get; set; }
        public Nullable<decimal> px { get; set; }
        public Nullable<decimal> py { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
