//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCRIPTION
    {
        public int OBJECTID { get; set; }
        public string comment { get; set; }
        public string VerId { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public string GUID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
        public Nullable<int> Request_Type { get; set; }
        public Nullable<int> Object_Type { get; set; }
        public Nullable<int> Organizational_unit { get; set; }
        public string Request_Date { get; set; }
        public string Request_Code { get; set; }
        public string Controller_User { get; set; }
        public Nullable<int> Control_Result { get; set; }
        public string Control_Date { get; set; }
    }
}
