//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVPG_LVTABLET
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string HPLID { get; set; }
        public string HDLID { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public string Tablet_LocationID { get; set; }
        public Nullable<int> Tablet_Kind { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> Famous_Flow { get; set; }
        public Nullable<int> AccessKind { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Hight { get; set; }
        public Nullable<int> Extend_Posibility { get; set; }
        public string Constructor_Name { get; set; }
        public Nullable<int> Tablet_Genus { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<int> Plat_Kind { get; set; }
        public Nullable<int> Lustr_Meter { get; set; }
        public Nullable<int> Register { get; set; }
        public Nullable<int> Change_over { get; set; }
        public Nullable<int> Earth { get; set; }
        public Nullable<decimal> Earth_Resistance { get; set; }
        public string Earth_measure_Date { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string VerID { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public string HV_PostUID { get; set; }
        public string ArrayPoint { get; set; }
        public Nullable<System.Guid> GlobalID2 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
