//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVPL_UGLINE
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string HPLID { get; set; }
        public string HDLID { get; set; }
        public string Constructor_Name { get; set; }
        public Nullable<decimal> Cable_Length { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<int> UG_Composite { get; set; }
        public Nullable<int> Damper_Kind { get; set; }
        public Nullable<int> Cable_Kind { get; set; }
        public Nullable<int> Phase_Core_Cnt { get; set; }
        public Nullable<decimal> OnLineLoad { get; set; }
        public Nullable<decimal> MaxLoad { get; set; }
        public Nullable<int> Joint { get; set; }
        public Nullable<decimal> Joint_Distance { get; set; }
        public Nullable<int> Lustr_Composite { get; set; }
        public Nullable<decimal> Cable_Depth { get; set; }
        public Nullable<int> Phase_Decor { get; set; }
        public Nullable<int> Cable_Relay { get; set; }
        public Nullable<int> Gather_Kind { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> px { get; set; }
        public Nullable<decimal> py { get; set; }
        public Nullable<decimal> cx { get; set; }
        public Nullable<decimal> cy { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public string PName { get; set; }
        public string CName { get; set; }
        public string Section_Name { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public Nullable<int> bd1 { get; set; }
        public Nullable<int> bd2 { get; set; }
        public Nullable<int> bd3 { get; set; }
        public Nullable<int> CS { get; set; }
        public string IPxyz { get; set; }
        public string ICxyz { get; set; }
        public Nullable<System.Guid> GlobalID2 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
