//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVPT_PARTNERPLAQUE
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string HPLID { get; set; }
        public string HDLID { get; set; }
        public Nullable<int> PartnerUserID { get; set; }
        public string CityRegion { get; set; }
        public string RegionCode { get; set; }
        public string ReqNO { get; set; }
        public Nullable<int> ReqStatus { get; set; }
        public string ReqDtae { get; set; }
        public string ReqAddress { get; set; }
        public string ReqFName { get; set; }
        public string ReqLName { get; set; }
        public Nullable<int> ReqMelliCode { get; set; }
        public Nullable<int> ReqTelNO { get; set; }
        public Nullable<decimal> ReqMobileNO { get; set; }
        public Nullable<int> ReqKind { get; set; }
        public Nullable<int> ReqKontor { get; set; }
        public Nullable<int> Install_Location { get; set; }
        public Nullable<int> Partner_Cnt { get; set; }
        public Nullable<int> Meter_Max { get; set; }
        public Nullable<int> WorkDay { get; set; }
        public Nullable<int> Operator { get; set; }
        public string OperatorState { get; set; }
        public Nullable<int> ForkKind { get; set; }
        public Nullable<int> Phase_Cnt { get; set; }
        public Nullable<int> Voltage { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<int> Amper { get; set; }
        public Nullable<int> ConsumeKind { get; set; }
        public Nullable<int> Situation { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<int> InstallationReq { get; set; }
        public Nullable<int> FrontageStatus { get; set; }
        public Nullable<decimal> CableService_Length { get; set; }
        public Nullable<decimal> CableService_Area { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public string GUID2 { get; set; }
        public string PartnerID { get; set; }
        public Nullable<System.Guid> GlobalID2 { get; set; }
        public string MAXIMETER { get; set; }
        public string DEMAND { get; set; }
        public string ESHTERAK { get; set; }
        public string SHENASAEE { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
        public string creation_date { get; set; }
        public string ramz { get; set; }
        public string Billing_ID { get; set; }
        public Nullable<int> Type_meter { get; set; }
        public Nullable<int> Branching_condition { get; set; }
        public Nullable<int> Usage_group { get; set; }
        public Nullable<int> karbari { get; set; }
        public Nullable<int> Organization { get; set; }
        public Nullable<int> Class { get; set; }
        public Nullable<int> Tariffs { get; set; }
    }
}
