//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVPT_INSULATOR
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string HPLID { get; set; }
        public string HDLID { get; set; }
        public Nullable<int> Insulator_Composite { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public string Constructor_Name { get; set; }
        public Nullable<int> Lustr_phase { get; set; }
        public Nullable<int> Decor { get; set; }
        public Nullable<int> PartnerR { get; set; }
        public Nullable<int> PartnerS { get; set; }
        public Nullable<int> PartnerT { get; set; }
        public Nullable<int> Earth { get; set; }
        public string Earth_Meter_Date { get; set; }
        public Nullable<decimal> Earth_Resistance { get; set; }
        public Nullable<decimal> VoltageR { get; set; }
        public Nullable<decimal> VoltageS { get; set; }
        public Nullable<decimal> VoltageT { get; set; }
        public Nullable<decimal> VoltageN { get; set; }
        public string Voltage_Meter_Date { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
