//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVPT_AVENUELUSTR
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string HPLID { get; set; }
        public string HDLID { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public string Lustr_Constructor { get; set; }
        public Nullable<int> Feeder_Phase { get; set; }
        public Nullable<decimal> Location_Height { get; set; }
        public Nullable<int> Arm_Length { get; set; }
        public Nullable<int> Bulb_Kind { get; set; }
        public Nullable<int> Lamp_Kind { get; set; }
        public Nullable<int> Pole_Kind { get; set; }
        public Nullable<int> Bulb_Type { get; set; }
        public Nullable<int> Bulb_Cnt { get; set; }
        public Nullable<decimal> Bulb_Power { get; set; }
        public Nullable<decimal> Lamp_Power { get; set; }
        public Nullable<decimal> Bulb_Angle { get; set; }
        public Nullable<int> Protect_Kind { get; set; }
        public string Pole_Insulator { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
