//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class LVPT_FUSEKEY
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string HPLID { get; set; }
        public string HDLID { get; set; }
        public string Measure_Date { get; set; }
        public string Constructor_Name { get; set; }
        public Nullable<int> Key_Kind { get; set; }
        public Nullable<int> Fuse_Kind { get; set; }
        public Nullable<int> Famous_Flow { get; set; }
        public Nullable<int> Relation_Status { get; set; }
        public Nullable<int> Using_Kind { get; set; }
        public Nullable<decimal> FlowMaxR { get; set; }
        public Nullable<decimal> FlowMaxS { get; set; }
        public Nullable<decimal> FlowMaxT { get; set; }
        public Nullable<decimal> FlowMaxN { get; set; }
        public Nullable<decimal> VoltMaxR { get; set; }
        public Nullable<decimal> VoltMaxS { get; set; }
        public Nullable<decimal> VoltMaxT { get; set; }
        public Nullable<decimal> FlowOnLineR { get; set; }
        public Nullable<decimal> FlowOnLineS { get; set; }
        public Nullable<decimal> FlowOnLineT { get; set; }
        public Nullable<decimal> FlowOnLineN { get; set; }
        public Nullable<decimal> VoltOnLineR { get; set; }
        public Nullable<decimal> VoltOnLineS { get; set; }
        public Nullable<decimal> VoltOnLineT { get; set; }
        public string BoardID { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public string Measure_Time { get; set; }
        public Nullable<decimal> Pload_KW { get; set; }
        public Nullable<decimal> VSOURCE_LI { get; set; }
        public Nullable<decimal> V_min_Feed { get; set; }
        public Nullable<decimal> PF { get; set; }
        public Nullable<int> Fuse_Nom_R { get; set; }
        public Nullable<int> Fuse_Nom_S { get; set; }
        public Nullable<int> Fuse_Nom_T { get; set; }
        public Nullable<System.Guid> GlobalID2 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
