//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPG_LAND
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public string LandID { get; set; }
        public string MaliCode { get; set; }
        public string Address { get; set; }
        public string PostCode { get; set; }
        public Nullable<decimal> longitude { get; set; }
        public Nullable<decimal> latitude { get; set; }
        public Nullable<decimal> BareArea { get; set; }
        public Nullable<decimal> LandWorth { get; set; }
        public Nullable<int> Structure { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<int> StructKind { get; set; }
        public Nullable<decimal> NoblesArea { get; set; }
        public Nullable<int> FloorCnt { get; set; }
        public Nullable<int> UnitCnt { get; set; }
        public Nullable<int> StructPermit { get; set; }
        public Nullable<decimal> StructWorth { get; set; }
        public string PostID { get; set; }
        public Nullable<int> PostStatus { get; set; }
        public Nullable<int> OwnerStatus { get; set; }
        public string OfficeNo { get; set; }
        public string SecondaryAlley { get; set; }
        public string PrimaryAlley { get; set; }
        public string RegisterNo { get; set; }
        public string RegisterDate { get; set; }
        public Nullable<int> PartnerElec { get; set; }
        public string PartnerElecNo { get; set; }
        public Nullable<int> PartnerWatter { get; set; }
        public string PartnerWatterNo { get; set; }
        public Nullable<int> PartnerGaz { get; set; }
        public string PartnerGazNo { get; set; }
        public Nullable<int> PartnerTel { get; set; }
        public Nullable<decimal> PartnerTelNO { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string U_ID { get; set; }
        public string VerID { get; set; }
        public string GUID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
