//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPL_OVHLINE
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string Conductor_Constructor { get; set; }
        public Nullable<int> Conductor_Composite { get; set; }
        public Nullable<int> Circut_Max { get; set; }
        public Nullable<int> Circut_Current_Cnt { get; set; }
        public Nullable<int> Spacer { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<decimal> Length { get; set; }
        public Nullable<decimal> Loadmax { get; set; }
        public Nullable<decimal> LoadOnLine { get; set; }
        public Nullable<decimal> px { get; set; }
        public Nullable<decimal> py { get; set; }
        public Nullable<decimal> cx { get; set; }
        public Nullable<decimal> cy { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public string PName { get; set; }
        public string CName { get; set; }
        public string Section_Name { get; set; }
        public string IPxyz { get; set; }
        public string ICxyz { get; set; }
        public Nullable<int> CS { get; set; }
        public Nullable<int> bd1 { get; set; }
        public Nullable<int> bd2 { get; set; }
        public Nullable<int> bd3 { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public Nullable<System.Guid> GlobalID2 { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
