//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_HEADER
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string DispaCode { get; set; }
        public string Trans_ID { get; set; }
        public Nullable<int> TransCode { get; set; }
        public Nullable<int> FeederKind { get; set; }
        public Nullable<int> FeederStatus { get; set; }
        public Nullable<int> UsingYear { get; set; }
        public Nullable<int> OwnerCity1 { get; set; }
        public Nullable<decimal> LoadPercentCity1 { get; set; }
        public Nullable<int> OwnerCity2 { get; set; }
        public Nullable<decimal> LoadPercentCity2 { get; set; }
        public Nullable<int> OwnerCity3 { get; set; }
        public Nullable<decimal> LoadPercentCity3 { get; set; }
        public Nullable<int> OwnerCity4 { get; set; }
        public Nullable<decimal> LoadPercentCity4 { get; set; }
        public Nullable<int> Header_Kind { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<int> Install_Kind { get; set; }
        public Nullable<int> Header_Size { get; set; }
        public Nullable<int> Header_Earth { get; set; }
        public string Constructor_Name { get; set; }
        public Nullable<int> Famous_Voltage { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string HVSUBUID { get; set; }
        public string FeederName { get; set; }
        public string HVSUBSTATION_Name { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
