//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_COLONY
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string Address { get; set; }
        public Nullable<int> NetDecor_Composite { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> Connection { get; set; }
        public Nullable<decimal> Voltage_KV { get; set; }
        public Nullable<decimal> Voltage_PU { get; set; }
        public Nullable<int> Cross_Genus1 { get; set; }
        public Nullable<int> Cross_Genus2 { get; set; }
        public Nullable<int> Cross_Size1 { get; set; }
        public Nullable<int> Cross_Size2 { get; set; }
        public Nullable<int> Cross_Length1 { get; set; }
        public Nullable<int> Cross_Length2 { get; set; }
        public Nullable<int> Cross_Cnt1 { get; set; }
        public Nullable<int> Cross_Cnt2 { get; set; }
        public Nullable<int> Insulator_Genus1 { get; set; }
        public Nullable<int> Insulator_Genus2 { get; set; }
        public Nullable<int> Insulator_Kind1 { get; set; }
        public Nullable<int> Insulator_Kind2 { get; set; }
        public Nullable<int> Insulator_Base1 { get; set; }
        public Nullable<int> Insulator_Base2 { get; set; }
        public Nullable<int> Insulator_VLevel1 { get; set; }
        public Nullable<int> Insulator_VLevel2 { get; set; }
        public Nullable<int> Insulator_Elastic_Power1 { get; set; }
        public Nullable<int> Insulator_Elastic_Power2 { get; set; }
        public Nullable<int> Insulator_Dish_Cnt1 { get; set; }
        public Nullable<int> Insulator_Dish_Cnt2 { get; set; }
        public Nullable<int> Elavator { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public string POLEUID { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public string Cyme_Equal { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
