//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_HVSUBSTATIONTRANS
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public string HVSUBSTATION_Name { get; set; }
        public string SerialNo { get; set; }
        public string Address { get; set; }
        public string Constructor_Name { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Manufactory_Name { get; set; }
        public Nullable<int> Cooler { get; set; }
        public Nullable<int> Vector_Group { get; set; }
        public Nullable<int> Connection { get; set; }
        public Nullable<decimal> UK_Percent { get; set; }
        public Nullable<int> Diskette { get; set; }
        public Nullable<int> Termometer { get; set; }
        public Nullable<int> Teremos { get; set; }
        public Nullable<int> First_Voltage { get; set; }
        public Nullable<int> Second_Voltage { get; set; }
        public Nullable<decimal> Impedance { get; set; }
        public Nullable<int> Tap_Cnt { get; set; }
        public Nullable<int> Tap_Status { get; set; }
        public Nullable<int> Tap_Location { get; set; }
        public Nullable<int> Tap_Changer { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string HVSUBUID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
