//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_POLESUBSTATION
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string Post_Name { get; set; }
        public string Post_Address { get; set; }
        public Nullable<int> Year_Install { get; set; }
        public Nullable<decimal> LoadingAmount { get; set; }
        public Nullable<decimal> LoadingPercent { get; set; }
        public Nullable<decimal> LoadingFactor { get; set; }
        public string LoadingDate { get; set; }
        public Nullable<int> LoadingKind { get; set; }
        public Nullable<int> Owner { get; set; }
        public string Post_code { get; set; }
        public Nullable<int> Implement_Kind { get; set; }
        public Nullable<int> Trans_Platform_Size { get; set; }
        public Nullable<int> Clamp_Kind { get; set; }
        public Nullable<decimal> Cns_Home { get; set; }
        public Nullable<decimal> Cns_Public { get; set; }
        public Nullable<decimal> Cns_Business { get; set; }
        public Nullable<decimal> Cns_Pasaj { get; set; }
        public Nullable<decimal> Cns_Stone { get; set; }
        public Nullable<decimal> Cns_Train { get; set; }
        public Nullable<decimal> Cns_Indust { get; set; }
        public Nullable<decimal> Cns_Lustr { get; set; }
        public Nullable<decimal> Cns_Agri { get; set; }
        public Nullable<decimal> Cns_Village { get; set; }
        public Nullable<decimal> Cns_Work { get; set; }
        public Nullable<decimal> Cns_Nonmotori { get; set; }
        public Nullable<decimal> Cns_Oven { get; set; }
        public Nullable<decimal> Cns_Hospital { get; set; }
        public string T_SerialNo { get; set; }
        public Nullable<int> T_Year_Constract { get; set; }
        public string T_Constractor_Name { get; set; }
        public Nullable<int> T_AirCondition_Kind { get; set; }
        public Nullable<int> T_Dead_Kind { get; set; }
        public Nullable<int> T_Tap_Cnt { get; set; }
        public Nullable<int> T_Capacity { get; set; }
        public Nullable<int> T_Tap_Regulated_No { get; set; }
        public Nullable<int> T_Ternometer { get; set; }
        public Nullable<int> T_Silica_Hole { get; set; }
        public Nullable<int> T_Vector { get; set; }
        public Nullable<int> T_UK_Percent { get; set; }
        public Nullable<decimal> T_Thermos_Temp { get; set; }
        public Nullable<int> T_Disc { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string GUID2 { get; set; }
        public string ID { get; set; }
        public string Coding { get; set; }
        public string FeederName { get; set; }
        public string TARIKH_Bar { get; set; }
        public string Time_Bar { get; set; }
        public Nullable<decimal> PLOAD_KW { get; set; }
        public Nullable<decimal> VSOURCE_LI { get; set; }
        public Nullable<decimal> I_R { get; set; }
        public Nullable<decimal> I_S { get; set; }
        public Nullable<decimal> I_T { get; set; }
        public Nullable<decimal> I_N { get; set; }
        public Nullable<System.Guid> GlobalID2 { get; set; }
        public Nullable<int> Owner_City { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
