//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_AUTOBOOSTER
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string Address { get; set; }
        public string Constructor_Name { get; set; }
        public string SerialNo { get; set; }
        public string Model { get; set; }
        public Nullable<int> Deploy_Kind { get; set; }
        public Nullable<int> Config_Type { get; set; }
        public Nullable<int> Config_Point_Cnt { get; set; }
        public Nullable<decimal> Up_Current_Config { get; set; }
        public Nullable<decimal> Down_Current_Config { get; set; }
        public Nullable<int> Connect_Status { get; set; }
        public Nullable<decimal> Max_Voltage_Up { get; set; }
        public Nullable<decimal> Max_Voltage_Down { get; set; }
        public Nullable<decimal> Flow_Range { get; set; }
        public Nullable<decimal> Max_Flow_A { get; set; }
        public Nullable<decimal> Config_Range_A { get; set; }
        public Nullable<decimal> Max_Flow_B { get; set; }
        public Nullable<decimal> Config_Range_B { get; set; }
        public Nullable<decimal> Max_Flow_C { get; set; }
        public Nullable<decimal> Config_Range_C { get; set; }
        public Nullable<decimal> Max_Flow_D { get; set; }
        public Nullable<decimal> Config_Range_D { get; set; }
        public Nullable<int> Connect_Kind { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
