//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_EARTH
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string Address { get; set; }
        public string Rod_Constructor_Name { get; set; }
        public Nullable<int> Rod_Constructor_Year { get; set; }
        public Nullable<int> Rod_Install_Year { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Rod_Kind { get; set; }
        public Nullable<int> Rod_Insulator_genus { get; set; }
        public Nullable<int> Rod_TabletKind { get; set; }
        public Nullable<int> Disconnector { get; set; }
        public Nullable<int> Earth_Area { get; set; }
        public Nullable<decimal> Earth_Resistance { get; set; }
        public string Earth_Date { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
