//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_FRONTAGE
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string Address { get; set; }
        public Nullable<int> Kind { get; set; }
        public string survey_Date { get; set; }
        public Nullable<decimal> ExceedDistance { get; set; }
        public Nullable<decimal> DeviceSpecific { get; set; }
        public Nullable<decimal> DesignImprove { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> triming { get; set; }
        public Nullable<int> TreeCount { get; set; }
        public Nullable<decimal> EngageCost { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string RunningDastoorNo { get; set; }
        public Nullable<int> EliminationFrontage { get; set; }
        public string EliminationDate { get; set; }
        public string Comment { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
