//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_PADSUBSTATIONTRANS
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string SerialNo { get; set; }
        public string Constructor_Name { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<decimal> LoadingAmount { get; set; }
        public Nullable<decimal> LoadingPercent { get; set; }
        public Nullable<decimal> LoadingFactor { get; set; }
        public string LoadingDate { get; set; }
        public Nullable<int> LoadingKind { get; set; }
        public Nullable<int> Owner { get; set; }
        public Nullable<int> Trans_AirCondition_Kind { get; set; }
        public Nullable<int> Famous_Capacity { get; set; }
        public Nullable<decimal> Termos_Temp { get; set; }
        public Nullable<int> Ternometer { get; set; }
        public Nullable<int> Disc { get; set; }
        public Nullable<int> Tap_Cnt { get; set; }
        public Nullable<int> UK_Percent { get; set; }
        public Nullable<int> Vector_Group { get; set; }
        public Nullable<int> Silica_Hole { get; set; }
        public Nullable<int> Tap_Regulated_No { get; set; }
        public Nullable<int> Trans_Dead_Kind { get; set; }
        public Nullable<int> Termos { get; set; }
        public Nullable<int> Relay { get; set; }
        public Nullable<decimal> CNS_Home { get; set; }
        public Nullable<decimal> CNS_Public { get; set; }
        public Nullable<decimal> CNS_Business { get; set; }
        public Nullable<decimal> CNS_Pasaj { get; set; }
        public Nullable<decimal> CNS_Stone { get; set; }
        public Nullable<decimal> CNS_Train { get; set; }
        public Nullable<decimal> CNS_Indust { get; set; }
        public Nullable<decimal> CNS_Lustr { get; set; }
        public Nullable<decimal> CNS_Agri { get; set; }
        public Nullable<decimal> CNS_Village { get; set; }
        public Nullable<decimal> CNS_Work { get; set; }
        public Nullable<decimal> CNS_NonMotori { get; set; }
        public Nullable<decimal> CNS_Oven { get; set; }
        public Nullable<decimal> CNS_Hospital { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string PADSUBUID { get; set; }
        public string FeederName { get; set; }
        public string Post_Code { get; set; }
        public string Post_Address { get; set; }
        public Nullable<int> Post_Kind { get; set; }
        public string TARIKH_Bar { get; set; }
        public string Time_Bar { get; set; }
        public Nullable<decimal> PLOAD_KW { get; set; }
        public Nullable<decimal> VSOURCE_LI { get; set; }
        public Nullable<decimal> I_R { get; set; }
        public Nullable<decimal> I_S { get; set; }
        public Nullable<decimal> I_T { get; set; }
        public Nullable<decimal> I_N { get; set; }
        public Nullable<System.Guid> GlobalID2 { get; set; }
        public Nullable<int> Owner_City { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
