//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class MVPT_AUTORECLOSER
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string Address { get; set; }
        public string Constructor_Name { get; set; }
        public string Model { get; set; }
        public Nullable<int> Using_Kind { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<decimal> One_Regulated_Time { get; set; }
        public Nullable<decimal> Two_Regulated_Time { get; set; }
        public Nullable<decimal> Three_Regulated_Time { get; set; }
        public Nullable<decimal> Four_Regulated_Time { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> Cut_Cnt { get; set; }
        public Nullable<int> Key_Kind { get; set; }
        public Nullable<decimal> Cut_Flow_Max { get; set; }
        public Nullable<decimal> Famous_Flow { get; set; }
        public Nullable<decimal> OnLineLoad { get; set; }
        public Nullable<int> Relay_Arc { get; set; }
        public Nullable<decimal> Operation_Time { get; set; }
        public string Reset_Time { get; set; }
        public Nullable<decimal> Cut_MaxFlow { get; set; }
        public string Cut_Direction { get; set; }
        public Nullable<int> Install_Year { get; set; }
        public Nullable<int> Constructor_Year { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public Nullable<int> U_ID { get; set; }
        public string U_Date { get; set; }
        public string U_Time { get; set; }
        public string VerID { get; set; }
        public Nullable<decimal> Angel { get; set; }
        public string GUID { get; set; }
        public string FeederName { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public Nullable<int> Design { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
