//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIS.Class
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWCUSTOMERREQUEST
    {
        public int OBJECTID { get; set; }
        public Nullable<int> CityNID { get; set; }
        public Nullable<int> HyperNID { get; set; }
        public Nullable<int> HeaderNID { get; set; }
        public string HPLID { get; set; }
        public string HDLID { get; set; }
        public string CityRegion { get; set; }
        public string ReqNO { get; set; }
        public Nullable<int> ReqStatus { get; set; }
        public string ReqDtae { get; set; }
        public string ReqAddress { get; set; }
        public string ReqFName { get; set; }
        public string ReqMobileNO { get; set; }
        public Nullable<int> ReqKind { get; set; }
        public Nullable<int> ReqKontor { get; set; }
        public Nullable<int> ForkKind { get; set; }
        public Nullable<int> Phase_Cnt { get; set; }
        public Nullable<int> Voltage { get; set; }
        public Nullable<int> Power { get; set; }
        public Nullable<int> ConsumeKind { get; set; }
        public Nullable<int> Situation { get; set; }
        public Nullable<int> Limit { get; set; }
        public Nullable<int> InstallationReq { get; set; }
        public Nullable<int> FrontageStatus { get; set; }
        public Nullable<decimal> x { get; set; }
        public Nullable<decimal> y { get; set; }
        public string GUID { get; set; }
        public string ESHTERAK { get; set; }
        public string SHENASAEE { get; set; }
        public string C_ID { get; set; }
        public string U_Time { get; set; }
        public string U_ID { get; set; }
        public string U_Date { get; set; }
        public System.Data.Entity.Spatial.DbGeometry SHAPE { get; set; }
        public string created_user { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string last_edited_user { get; set; }
        public Nullable<System.DateTime> last_edited_date { get; set; }
    }
}
