using System;
public class LVPL_UGLINE
{
    public int OBJECTID { get; set; }
    public int? CityNID { get; set; }
    public int? HyperNID { get; set; }
    public int? HeaderNID { get; set; }
    public string HPLID { get; set; }
    public string HDLID { get; set; }
    public string Constructor_Name { get; set; }
    public decimal? Cable_Length { get; set; }
    public int? Constructor_Year { get; set; }
    public int? UG_Composite { get; set; }
    public int? Damper_Kind { get; set; }
    public int? Cable_Kind { get; set; }
    public int? Phase_Core_Cnt { get; set; }
    public decimal? OnLineLoad { get; set; }
    public decimal? MaxLoad { get; set; }
    public int? Joint { get; set; }
    public decimal? Joint_Distance { get; set; }
    public int? Lustr_Composite { get; set; }
    public decimal? Cable_Depth { get; set; }
    public int? Phase_Decor { get; set; }
    public int? Cable_Relay { get; set; }
    public int? Gather_Kind { get; set; }
    public int? Install_Year { get; set; }
    public decimal? Length { get; set; }
    public decimal? px { get; set; }
    public decimal? py { get; set; }
    public decimal? cx { get; set; }
    public decimal? cy { get; set; }
    public int? U_ID { get; set; }
    public string U_Date { get; set; }
    public string U_Time { get; set; }
    public string VerID { get; set; }
    public string PName { get; set; }
    public string CName { get; set; }
    public string Section_Name { get; set; }
    public string GUID { get; set; }
    public string FeederName { get; set; }
    public int? bd1 { get; set; }
    public int? bd2 { get; set; }
    public int? bd3 { get; set; }
    public int? CS { get; set; }
    public string IPxyz { get; set; }
    public string ICxyz { get; set; }
    public Guid? GlobalID2 { get; set; }
    public Microsoft.SqlServer.Types.SqlGeometry SHAPE { get; set; }
    public int? Design { get; set; }
    public string created_user { get; set; }
    public DateTime? created_date { get; set; }
    public string last_edited_user { get; set; }
    public DateTime? last_edited_date { get; set; }
}
