using System;
public class LVPT_PARTNERPLAQUE
{
    public int OBJECTID { get; set; }
    public int? CityNID { get; set; }
    public int? HyperNID { get; set; }
    public int? HeaderNID { get; set; }
    public string HPLID { get; set; }
    public string HDLID { get; set; }
    public int? PartnerUserID { get; set; }
    public string CityRegion { get; set; }
    public string RegionCode { get; set; }
    public string ReqNO { get; set; }
    public int? ReqStatus { get; set; }
    public string ReqDtae { get; set; }
    public string ReqAddress { get; set; }
    public string ReqFName { get; set; }
    public string ReqLName { get; set; }
    public int? ReqMelliCode { get; set; }
    public int? ReqTelNO { get; set; }
    public decimal? ReqMobileNO { get; set; }
    public int? ReqKind { get; set; }
    public int? ReqKontor { get; set; }
    public int? Install_Location { get; set; }
    public int? Partner_Cnt { get; set; }
    public int? Meter_Max { get; set; }
    public int? WorkDay { get; set; }
    public int? Operator { get; set; }
    public string OperatorState { get; set; }
    public int? ForkKind { get; set; }
    public int? Phase_Cnt { get; set; }
    public int? Voltage { get; set; }
    public int? Power { get; set; }
    public int? Amper { get; set; }
    public int? ConsumeKind { get; set; }
    public int? Situation { get; set; }
    public int? Limit { get; set; }
    public int? InstallationReq { get; set; }
    public int? FrontageStatus { get; set; }
    public decimal? CableService_Length { get; set; }
    public decimal? CableService_Area { get; set; }
    public decimal? x { get; set; }
    public decimal? y { get; set; }
    public int? U_ID { get; set; }
    public string U_Date { get; set; }
    public string U_Time { get; set; }
    public string VerID { get; set; }
    public decimal? Angel { get; set; }
    public string GUID { get; set; }
    public string FeederName { get; set; }
    public string GUID2 { get; set; }
    public string PartnerID { get; set; }
    public Guid? GlobalID2 { get; set; }
    public string MAXIMETER { get; set; }
    public string DEMAND { get; set; }
    public string ESHTERAK { get; set; }
    public string SHENASAEE { get; set; }
    public Microsoft.SqlServer.Types.SqlGeometry SHAPE { get; set; }
    public int? Design { get; set; }
    public string created_user { get; set; }
    public DateTime? created_date { get; set; }
    public string last_edited_user { get; set; }
    public DateTime? last_edited_date { get; set; }
    public string creation_date { get; set; }
    public string ramz { get; set; }
    public string Billing_ID { get; set; }
    public int? Type_meter { get; set; }
    public int? Branching_condition { get; set; }
    public int? Usage_group { get; set; }
    public int? karbari { get; set; }
    public int? Organization { get; set; }
    public int? Class { get; set; }
    public int? Tariffs { get; set; }
}
