using System;
public class LVPT_AUTOKEY
{
    public int OBJECTID { get; set; }
    public int? CityNID { get; set; }
    public int? HyperNID { get; set; }
    public int? HeaderNID { get; set; }
    public string HPLID { get; set; }
    public string HDLID { get; set; }
    public string HV_PostUID { get; set; }
    public string Tablet_LocationID { get; set; }
    public int? Key_Kind { get; set; }
    public int? Famous_Flow { get; set; }
    public string Constructor_Name { get; set; }
    public int? usage_Kind { get; set; }
    public int? RelayKind { get; set; }
    public int? Load_Relay_Factor { get; set; }
    public int? SC_Relay_Factor { get; set; }
    public string Measure_Date { get; set; }
    public decimal? FlowMaxR { get; set; }
    public decimal? FlowMaxS { get; set; }
    public decimal? FlowMaxT { get; set; }
    public decimal? FlowMaxN { get; set; }
    public decimal? VoltMaxR { get; set; }
    public decimal? VoltMaxS { get; set; }
    public decimal? VoltMaxT { get; set; }
    public decimal? FlowOnLineR { get; set; }
    public decimal? FlowOnLineS { get; set; }
    public decimal? FlowOnLineT { get; set; }
    public decimal? FlowOnLineN { get; set; }
    public decimal? VoltOnLineR { get; set; }
    public decimal? VoltOnLineS { get; set; }
    public decimal? VoltOnLineT { get; set; }
    public decimal? x { get; set; }
    public decimal? y { get; set; }
    public int? U_ID { get; set; }
    public string U_Date { get; set; }
    public string U_Time { get; set; }
    public string VerID { get; set; }
    public decimal? Angel { get; set; }
    public string GUID { get; set; }
    public string FeederName { get; set; }
    public string Measure_Time { get; set; }
    public decimal? Pload_KW { get; set; }
    public decimal? VSOURCE_LI { get; set; }
    public decimal? V_min_Feed { get; set; }
    public decimal? PF { get; set; }
    public Guid? GlobalID2 { get; set; }
    public Microsoft.SqlServer.Types.SqlGeometry SHAPE { get; set; }
    public int? Design { get; set; }
    public string created_user { get; set; }
    public DateTime? created_date { get; set; }
    public string last_edited_user { get; set; }
    public DateTime? last_edited_date { get; set; }
}
