using System;
public class MVPT_PADSUBSTATIONTRANS
{
    public int OBJECTID { get; set; }
    public int? CityNID { get; set; }
    public int? HyperNID { get; set; }
    public int? HeaderNID { get; set; }
    public string SerialNo { get; set; }
    public string Constructor_Name { get; set; }
    public int? Constructor_Year { get; set; }
    public int? Install_Year { get; set; }
    public decimal? LoadingAmount { get; set; }
    public decimal? LoadingPercent { get; set; }
    public decimal? LoadingFactor { get; set; }
    public string LoadingDate { get; set; }
    public int? LoadingKind { get; set; }
    public int? Owner { get; set; }
    public int? Trans_AirCondition_Kind { get; set; }
    public int? Famous_Capacity { get; set; }
    public decimal? Termos_Temp { get; set; }
    public int? Ternometer { get; set; }
    public int? Disc { get; set; }
    public int? Tap_Cnt { get; set; }
    public int? UK_Percent { get; set; }
    public int? Vector_Group { get; set; }
    public int? Silica_Hole { get; set; }
    public int? Tap_Regulated_No { get; set; }
    public int? Trans_Dead_Kind { get; set; }
    public int? Termos { get; set; }
    public int? Relay { get; set; }
    public decimal? CNS_Home { get; set; }
    public decimal? CNS_Public { get; set; }
    public decimal? CNS_Business { get; set; }
    public decimal? CNS_Pasaj { get; set; }
    public decimal? CNS_Stone { get; set; }
    public decimal? CNS_Train { get; set; }
    public decimal? CNS_Indust { get; set; }
    public decimal? CNS_Lustr { get; set; }
    public decimal? CNS_Agri { get; set; }
    public decimal? CNS_Village { get; set; }
    public decimal? CNS_Work { get; set; }
    public decimal? CNS_NonMotori { get; set; }
    public decimal? CNS_Oven { get; set; }
    public decimal? CNS_Hospital { get; set; }
    public decimal? x { get; set; }
    public decimal? y { get; set; }
    public int? U_ID { get; set; }
    public string U_Date { get; set; }
    public string U_Time { get; set; }
    public string VerID { get; set; }
    public decimal? Angel { get; set; }
    public string GUID { get; set; }
    public string PADSUBUID { get; set; }
    public string FeederName { get; set; }
    public string Post_Code { get; set; }
    public string Post_Address { get; set; }
    public int? Post_Kind { get; set; }
    public string TARIKH_Bar { get; set; }
    public string Time_Bar { get; set; }
    public decimal? PLOAD_KW { get; set; }
    public decimal? VSOURCE_LI { get; set; }
    public decimal? I_R { get; set; }
    public decimal? I_S { get; set; }
    public decimal? I_T { get; set; }
    public decimal? I_N { get; set; }
    public Guid? GlobalID2 { get; set; }
    public int? Owner_City { get; set; }
    public Microsoft.SqlServer.Types.SqlGeometry SHAPE { get; set; }
    public int? Design { get; set; }
    public string created_user { get; set; }
    public DateTime? created_date { get; set; }
    public string last_edited_user { get; set; }
    public DateTime? last_edited_date { get; set; }
}
