using System;
public class MVPT_POLESUBSTATION
{
    public int OBJECTID { get; set; }
    public int? CityNID { get; set; }
    public int? HyperNID { get; set; }
    public int? HeaderNID { get; set; }
    public string Post_Name { get; set; }
    public string Post_Address { get; set; }
    public int? Year_Install { get; set; }
    public decimal? LoadingAmount { get; set; }
    public decimal? LoadingPercent { get; set; }
    public decimal? LoadingFactor { get; set; }
    public string LoadingDate { get; set; }
    public int? LoadingKind { get; set; }
    public int? Owner { get; set; }
    public string Post_code { get; set; }
    public int? Implement_Kind { get; set; }
    public int? Trans_Platform_Size { get; set; }
    public int? Clamp_Kind { get; set; }
    public decimal? Cns_Home { get; set; }
    public decimal? Cns_Public { get; set; }
    public decimal? Cns_Business { get; set; }
    public decimal? Cns_Pasaj { get; set; }
    public decimal? Cns_Stone { get; set; }
    public decimal? Cns_Train { get; set; }
    public decimal? Cns_Indust { get; set; }
    public decimal? Cns_Lustr { get; set; }
    public decimal? Cns_Agri { get; set; }
    public decimal? Cns_Village { get; set; }
    public decimal? Cns_Work { get; set; }
    public decimal? Cns_Nonmotori { get; set; }
    public decimal? Cns_Oven { get; set; }
    public decimal? Cns_Hospital { get; set; }
    public string T_SerialNo { get; set; }
    public int? T_Year_Constract { get; set; }
    public string T_Constractor_Name { get; set; }
    public int? T_AirCondition_Kind { get; set; }
    public int? T_Dead_Kind { get; set; }
    public int? T_Tap_Cnt { get; set; }
    public int? T_Capacity { get; set; }
    public int? T_Tap_Regulated_No { get; set; }
    public int? T_Ternometer { get; set; }
    public int? T_Silica_Hole { get; set; }
    public int? T_Vector { get; set; }
    public int? T_UK_Percent { get; set; }
    public decimal? T_Thermos_Temp { get; set; }
    public int? T_Disc { get; set; }
    public decimal? x { get; set; }
    public decimal? y { get; set; }
    public int? U_ID { get; set; }
    public string U_Date { get; set; }
    public string U_Time { get; set; }
    public string VerID { get; set; }
    public decimal? Angel { get; set; }
    public string GUID { get; set; }
    public string GUID2 { get; set; }
    public string ID { get; set; }
    public string Coding { get; set; }
    public string FeederName { get; set; }
    public string TARIKH_Bar { get; set; }
    public string Time_Bar { get; set; }
    public decimal? PLOAD_KW { get; set; }
    public decimal? VSOURCE_LI { get; set; }
    public decimal? I_R { get; set; }
    public decimal? I_S { get; set; }
    public decimal? I_T { get; set; }
    public decimal? I_N { get; set; }
    public Guid? GlobalID2 { get; set; }
    public int? Owner_City { get; set; }
    public Microsoft.SqlServer.Types.SqlGeometry SHAPE { get; set; }
    public int? Design { get; set; }
    public string created_user { get; set; }
    public DateTime? created_date { get; set; }
    public string last_edited_user { get; set; }
    public DateTime? last_edited_date { get; set; }
}
